[server]
host = "127.0.0.1"
port = 8080

[app]
name = "DynServer"
log_level = "info"

[templates]
directory = "templates"

[static_files]
directory = "static"

[gallery]
path_prefix = "gallery"
source_directory = "/Users/atrus/Dropbox/Artwork/synced-images"
cache_directory = "cache/photos"
images_per_page = 2000
