[server]
host = "127.0.0.1"
port = 3000

[app]
name = "Tenrankai"
log_level = "info"
cookie_secret = "change-me-in-production-use-a-long-random-string"
copyright_holder = "Your Name"
base_url = "https://your-domain.com"
# Optional: Set user_database to enable authentication
# user_database = "users.toml"

[templates]
directory = "templates"

[static_files]
directory = "static"

# Configure one or more gallery systems
# Each gallery has its own source directory, URL prefix, and settings

# Main photo gallery
[[galleries]]
name = "photos"
url_prefix = "/gallery"
source_directory = "photos"
cache_directory = "cache/photos"
gallery_template = "modules/gallery.html.liquid"
image_detail_template = "modules/image_detail.html.liquid"
images_per_page = 50
cache_refresh_interval_minutes = 60
jpeg_quality = 85
webp_quality = 85.0
pregenerate_cache = false
# Number of days to consider an image as "new" (based on file modification date)
# Remove or comment out to disable the feature
new_threshold_days = 7

[galleries.thumbnail]
width = 300
height = 300

[galleries.gallery_size]
width = 800
height = 800

[galleries.medium]
width = 1200
height = 1200

[galleries.large]
width = 1600
height = 1600

[galleries.preview]
max_images = 6
max_depth = 3
max_per_folder = 3

# Example: Portfolio gallery with different settings
[[galleries]]
name = "portfolio"
url_prefix = "/portfolio"
source_directory = "portfolio_images"
cache_directory = "cache/portfolio"
gallery_template = "modules/gallery.html.liquid"
image_detail_template = "modules/image_detail.html.liquid"
images_per_page = 20
jpeg_quality = 90
webp_quality = 90.0

# Example: Screenshots gallery
[[galleries]]
name = "screenshots"
url_prefix = "/screenshots"
source_directory = "screenshots"
cache_directory = "cache/screenshots"
images_per_page = 100
# Custom templates can be specified
# gallery_template = "modules/screenshot_gallery.html.liquid"
# image_detail_template = "modules/screenshot_detail.html.liquid"

# Optional: Configure multiple post systems
# Each posts system has its own source directory and URL prefix
# You can have multiple systems like blog, stories, documentation, etc.

# Example blog configuration
[[posts]]
name = "blog"
source_directory = "posts/blog"
url_prefix = "/blog"
index_template = "modules/posts_index.html.liquid"
post_template = "modules/post_detail.html.liquid"
posts_per_page = 20

# Example stories configuration
[[posts]]
name = "stories"
source_directory = "posts/stories"
url_prefix = "/stories"
index_template = "modules/posts_index.html.liquid"
post_template = "modules/post_detail.html.liquid"
posts_per_page = 10

# Example instructions/documentation configuration
[[posts]]
name = "instructions"
source_directory = "posts/instructions"
url_prefix = "/instructions"
index_template = "modules/posts_index.html.liquid"
post_template = "modules/post_detail.html.liquid"
posts_per_page = 15