[server]
host = "127.0.0.1"
port = 8080

[app]
name = "Tenrankai"
log_level = "info"
cookie_secret = "your-secret-key-change-this-in-production-use-a-long-random-string"
base_url = "http://localhost:8080"
copyright_holder = "Yann Ramin. All rights reserved. theatr.us"
# No user_database specified - runs in no-auth mode

[templates]
directory = "templates"

[static_files]
directory = "static"

# Gallery configuration
[[galleries]]
name = "main"
url_prefix = "/gallery"
source_directory = "/Users/atrus/Dropbox/Artwork/synced-images"
cache_directory = "cache/photos"
images_per_page = 2000
cache_refresh_interval_minutes = 60
pregenerate_cache = true
new_threshold_days = 7
approximate_dates_for_public = false  # No need to hide dates when no auth

# Image resize configurations
[galleries.thumbnail]
width = 300
height = 300

[galleries.gallery_size]
width = 800
height = 800

[galleries.medium]
width = 1200
height = 1200

[galleries.large]
width = 1600
height = 1600

# Preview settings
[galleries.preview]
max_images = 4
max_depth = 3
max_per_folder = 3